/**
 * Copyright 2020, Saab AB
 *
 * This software may be distributed and modified according to 
 * the terms of the GNU General Public License version 2. 
 * Note that NO WARRANTY is provided.
 * See "LICENSE.GPLv2" for details.
 */
rom = 0x20000000;
ram = 0x80000000;
itim = 0x8000000;

CLIC  = 0x02000000;
PLIC  = 0x0C000000;
PRCI  = 0x10008000;
GPIO  = 0x10012000;
UART0 = 0x10013000;
UART1 = 0x10023000;
